openapi: 3.0.3
info:
  title: LKSH ADVANCED API
  version: 1.0.0
paths:
  /stats:
    get:
      summary: Получить статистику команды
      parameters:
        - in: query
          name: team_name
          schema:
            type: string
          required: true
          description: Название команды
      responses:
        '200':
          description: Статистика команды
          content:
            application/json:
              schema:
                type: object
                properties:
                  wins:
                    type: integer
                  losses:
                    type: integer
                  goal_diff:
                    type: integer
  /versus:
    get:
      summary: Получить количество матчей, где встречались два игрока
      parameters:
        - in: query
          name: player1_id
          schema:
            type: integer
          required: true
        - in: query
          name: player2_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Количество матчей
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: integer
  /goals:
    get:
      summary: Получить список голов игрока
      parameters:
        - in: query
          name: player_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Список голов
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    match:
                      type: integer
                    time:
                      type: integer
  /front/stats:
    get:
      summary: HTML-интерфейс статистики команд
      responses:
        '200':
          description: HTML страница
          content:
            text/html: {}
  /front/versus:
    get:
      summary: HTML-интерфейс для сравнения игроков
      responses:
        '200':
          description: HTML страница
          content:
            text/html: {}
